# global settings
site_name: WhatNot
site_author: gh-ka
site_description: >-
  Collecting bits and bytes
repo_name: gh-ka/whatnot
repo_url: https://github.com/gh-ka/whatnot
site_url: https://gh-ka.co/
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 gh-ka 

# use_directory_urls: false
# watch:
#   - tools

# theme
theme:
  name: material
  custom_dir: docs/_overrides       # customization
  favicon: assets/favicon.ico  
  palette:  
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  
  font:
    text: Roboto
    code: Roboto Mono
  
  icon:                       # various icons used 
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye  
    logo: logo
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      annotation: material/arrow-right-circle
  logo: assets/favicon.ico
  logo_bottom: assets/favicon.ico

  features:                     # get to know them :-)
    - announce.dismiss          # allow the viewer to close announcement bar
    - content.action.edit       # enable editing the content source   
    - content.action.view       # enable viewing the source
    - content.code.annotate     # enable code block annotate (?)
    - content.code.copy         # enable code block copy
    - content.code.select       # enable code block select (?)
    - content.tabs.link         # link all tabs in the page
    - content.tooltips          # (?)
    - content.footnote.tooltips # (?)
    - header.autohide           # (?)
    - navigation.expand
    - navigation.footer
    - navigation.indexes      # for blog indeces
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs         # tabs as content dividers
    - navigation.tabs.sticky  # tabs always visible
    - navigation.top          # show back-to-top button
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# markdown extensions
markdown_extensions:
  - abbr
  - admonition  # https://squidfunk.github.io/mkdocs-material/reference/admonitions
  # annotations
  # https://squidfunk.github.io/mkdocs-material/reference/annotations/
  # to turn links into buttons: [Send :fontawesome-solid-paper-plane:](#){ .md-button }
  - attr_list   
  - def_list
  - footnotes
  - md_in_html  # for annotations
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic     # was in my version
  - pymdownx.details    # needed for admonitions 
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight: # for codeblocks
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # for codeblocks
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: jxnl 
      repo: instructor
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets: # for codeblocks
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:    # for admonitions, annotations, content tabs, and codeblocks
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        # - name: md-render
        #   class: md-render
        #   format: !!python/name:tools.pymdownx_md_render.md_sub_render
        # - name: csv-path
        #   class: csv-path
        #   format: !!python/name:tools.pymdownx_md_render.md_csv_path_render
  - pymdownx.tabbed: # needed for content tabs
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - tables  # just to be sure, tables are enabled by default
  - toc:
      # baselevel: 2
      permalink: true
      separator: "_"      # ? was in my version

# nav 
# if there is no nav, all .md files are displayed
# otherwise, files must be included in nav to be displayed
# nav:
#   - WhatNot:
#     - Intro: "contents/index.md"
#     - Astro: "contents/astro/index.md"
#     - Knit:  "contents/knit/index.md"
#     - Tech:  "contents/tech/index.md"
#     - About: "contents/about/index.md"
#   - Astro:
#     - "contents/astro/index.md"
#   - Knit:
#     - "contents/knit/index.md"
#   - Tech:
#     - "contents/tech/index.md"
#   - About: 
#     - "contents/about/index.md"

# plugins
plugins:
  - blog:
      # enabled: !ENV CI
      blog_dir: contents/knit
      post_dir: contents/knit/posts
      blog_toc: true
      post_date_format: full
      post_url_format: "{date}/{slug}"
      # post_readtime_words_per_minute: 200
      archive_toc: true
      archive_name: Entries By Time
      archive_date_format: MMMM, yyyy
      archive_url_format: "{date}"
      categories_name: Entries By Topic
      categories_url_format: "{slug}"
      categories_toc: true
      #authors_file: "{blog}/.authors.yml"
  - blog:
      blog_dir: contents/astro
      post_dir: contents/astro/posts
      blog_toc: true
      post_date_format: full
      post_url_format: "{date}/{slug}"
      #post_readtime_words_per_minute: 200
      # archive_toc: true
      archive_name: Entries By Time
      archive_date_format: MMMM, yyyy
      archive_url_format: "{date}"
      categories_name: Entries by Topic
      categories_url_format: "{slug}"
      categories_toc: true
  - blog:
      blog_dir: contents/tech
      post_dir: contents/tech/posts
      blog_toc: true
      post_date_format: full
      post_url_format: "{date}/{slug}"
      #post_readtime_words_per_minute: 200
      # archive_toc: true
      archive_name: Entries By Time
      archive_date_format: MMMM, yyyy
      archive_url_format: "{date}"
      categories_name: Entries by Topic
      categories_url_format: "{slug}"
      categories_toc: true
  # - git-committers:
  #   enabled: !ENV [CI, false]
  #   repository: gh-ka/whatnot
  #   branch: main
  - glightbox
  - minify_html 
  # - minify:
  #     minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: alphabetical
            allow_inspection: true
            show_bases: true
          paths: [..]
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags

extra:
  # disqus docs:
  #   1. https://github.com/squidfunk/mkdocs-material/discussions/2138#discussioncomment-250454
  #   2. https://github.com/squidfunk/mkdocs-material/pull/3329#issuecomment-1013855846
  #   3. https://github.com/squidfunk/mkdocs-material/commit/f9e94184620806ceff55b6a8c2df0292b39369e4
  # disqus: copdips

  # analytics:
  #   provider: google
  #   property: G-686PKP2V2V
  social:
    # - icon: fontawesome/brands/twitter
    #   link: https://xxx
    - icon: fontawesome/brands/github
      link: https://github.com/gh-ka
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/xxx
    # - icon: material/email
    #   link: mailto:xxx@gmail.com
   
extra_css:
  - _css/extra.css

extra_javascript:
  - _js/mathjax.js
  - _js/analytics.js
  - _js/tablesort.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js