site_name: WhatNot
repo_url: https://github.com/gh-ka/whatnot
repo_name: gh-ka/whatnot
edit_uri: edit/main/docs/
nav:
  - Start Here:
    - About: "index.md"
    - Contact: 'contact.md'
  - HowTos:
    - "howtos/index.md"
  - Writing:
    - "writing/index.md"
  - Reading:
    - "reading/index.md"
  - Contact: 
    - "contact.md"
markdown_extensions:
  - toc:
      permalink: true
      baselevel: 2
      separator: "_"
plugins:
  - search
  - tags
  - blog:
      blog_dir: howtos
      blog_toc: true
      post_date_format: full
      post_url_format: "{date}/{slug}"
      post_readtime_words_per_minute: 200
      archive_toc: true
      archive_name: By Time
      archive_date_format: MMMM, yyyy
      archive_url_format: "{date}"
      categories_name: By Category
      categories_url_format: "{slug}"
      categories_toc: true
theme:
  name: material
  palette:  
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: orange
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye  
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs         # tabs as content dividers
    - navigation.tabs.sticky  # tabs always visible
    - navigation.top          # show back-to-top button
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view